# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a3214fdb5c653da566528eb37105c4716e412e8a6ff56fd3e25edca86e196375a68f5ef01aa85d1d957b99ab35d84bf149dda2452d28aabf3faab21c1632f9a

test:
  secret_key_base: 4f878a04cb0cbaa5d3fa4688772ce8131ee959ab63198fb2a6e248c0e267b097ac0ddc250853f2efee76d44d69ad62afefff5291c11ce3fa9201f31384529e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
